# Cloud Build configuration for Nexus-UMMID Demo UI
# Deploys static site to Cloud Run

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nexus-ummid-demo:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nexus-ummid-demo:latest'
      - '.'
    dir: 'apps/demo-ui'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nexus-ummid-demo:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nexus-ummid-demo:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nexus-ummid-demo'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nexus-ummid-demo:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/nexus-ummid-demo:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nexus-ummid-demo:latest'

options:
  logging: CLOUD_LOGGING_ONLY
